Dark Mode
adsabs/bumblebee pull request #2163
Opened 2021-05-18 16:35 UTC by shinyichen

* Added a dark mode switch on the right lower corner
* Remembers the setting in the local storage
* Uses system level dark mode preference if dark mode app setting not detected
* Dark mode CSS is applied based on `data-theme` attribute in the `body` tag.
* Dark mode CSS does not affect original CSS

![Screen Shot 2021-05-18 at 9 33 27 AM](https://user-images.githubusercontent.com/636361/118689666-1b055100-b7bc-11eb-8610-94ffe474195a.png)
![Screen Shot 2021-05-18 at 9 34 02 AM](https://user-images.githubusercontent.com/636361/118689751-31131180-b7bc-11eb-8249-d86f1594e7f8.png)

2021-05-19 18:12 UTC, thostetler requested changes
Nice work on the styling, this all looks great! :)
I think we'll just want to move your script into an actual module so it gets loaded properly and not ahead of more important things, etc.
Let me know if you need any help getting that to work.

2021-05-19 18:12 UTC, thostetler commented on src/js/dark-mode-switch.js
> +      localStorage.getItem('darkSwitch') !== null &&
We also technically already have a little wrapper around localstorage, you could bring it in in the header `define(['storage'], function (storage) { ... })`

2021-05-20 17:28 UTC, shinyichen commented on src/index.html
> +    <script src="js/dark-mode-switch.js"></script>
Done

2021-05-20 17:28 UTC, shinyichen commented on src/js/dark-mode-switch.js
> +(function() {
Done

2021-05-20 20:49 UTC, thostetler approved these changes
Updated changes look good to me, I'll merge

2021-05-20 20:50 UTC, merged