Improve resource timeout issue
adsabs/bumblebee pull request #2229
Opened 2022-01-23 08:10 UTC by thostetler

As a stopgap measure, this PR adds a seconds CDN fallback URL.  For the
time-being removes SRI for external links.
Also improves app loading messages

2022-01-24 18:45 UTC, shinyichen requested changes
The app does not start for me, it's looking for the `_setTimeout` function. Also in tests.

2022-01-24 18:45 UTC, shinyichen commented on src/js/components/application.js
> -    _setTimeout: function(deferred) {
Looks like tests still needs this function.

2022-01-24 18:45 UTC, shinyichen commented on src/js/components/application.js
> -    _setTimeout: function(deferred) {
Also I am seeing the missing function error in console log in dev

2022-01-24 22:59 UTC, thostetler commented
@shinyichen thanks for checking it out -- should hopefully be all fixed now.  Added a few updates also to the optimizer

2022-01-25 15:49 UTC, shinyichen approved these changes
I tested and didn't have any issues.

2022-01-25 16:42 UTC, merged